<fieldset class="login">
    <legend class="login__legend">ĐĂNG NHẬP</legend>
    <form class="login__form" name="frm_login" method="post">
        <label class="login__label" for="user[login]">Tên đăng nhập</label>
        <input class="login__input" type="text" name="user[login]" id="user[login]" maxlength="25">

        <label class="login__label" for="user[password]">Mật khẩu</label>
        <input class="login__input" type="password" id="user[password]" name="user[password]" maxlength="25">
       
        <button class="btn-light3d"  type="submit" data-action = "login">Đăng nhập</button>
        
        <div class="message message--error"></div>
    </form>
</fieldset>
    

