<fieldset class="login">
    <legend class="login__legend">ĐĂNG NHẬP</legend>
    <form class="login__form" name="frm_login_admin" method="post">
        <label class="login__label" for="user_name">Tên đăng nhập</label>
        <input class="login__input" type="text" name="user_name" id="user_name" maxlength="96">

        <label class="login__label" for="user_password">Mật khẩu</label>
        <input class="login__input" type="password" id="user_password" name="user_password" maxlength="96">

        <label class="login__label">Ảnh bảo mật</label>
        <img class="login__image" src="/capcha?response_type=image" security>

        <label class="login__label" for="imagesecurity">Nhập lại ảnh bảo mật</label>
        <input class="login__input" type="text" id="imagesecurity" name="imagesecurity" maxlength="5">

        <input class="login__checkbox" type="checkbox" id="setcookie" name="setcookie">
        <label class="login__label login__label--checkbox" for="setcookie">Lưu thông tin đăng nhập?&nbsp;</label>
        <button class="btn-light3d">Đăng nhập</button>
        <div class="message message--error"></div>
    </form>
</fieldset>
    

