<?php
    use Core\Utility\HtmlUtility;
?> 
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <?php $fragmentRenderer->renderPosition('title'); //title ?>
    <?php echo HtmlUtility::favicon('/lib_assets/images/logos/');//favicon ?>
    <?php $fragmentRenderer->renderPosition('css'); //css ?>
    <?php $fragmentRenderer->renderPosition('script'); //script ?>
</head>
<body>
    <?php echo HtmlUtility::toScriptLinks(PUBLIC_PATH, "/lib_assets/js/jcheck_cross_browser.js"); ?>
    <main>
        <?php $fragmentRenderer->renderPosition('left_main') ?>
        <?php //$fragmentRenderer->renderPosition('right_main') ?>
       
    </main>
</body>
</html>
